- db.json
- src/App.js
- src/components/ListEvents.js
- src/components/NewEvent.js
Create UI for adding a new event and save the created event to db.json
> Create new event

- src/App.js
- src/components/AppBar.js
- src/index.css
> navbar created, fixed to top

- .travis.yml
- package-lock.json
- package.json
- src/App.js
- src/components/AppBar.js
- src/components/NewEvent.js
Validation for form added and tweaked form a bit, date and time pickers, cancel clears the form.
> Validate event form

- src/components/EventCard.js
- src/components/ListEvents.js
- src/index.css
Hahmotelma siitä millainen event voisi olla. En viitsi tehdä enempää jos idea dumataan huonoksi.
> first draft of an event 'page'

- src/App.js
- src/components/EventCard.js
- src/components/NewEvent.js
Also fix warnings from console in frontend
> Catch error if backend is down

- .eslintrc.js
- package-lock.json
- package.json
- src/components/EventCard.js
- src/components/ListEvents.js
- src/components/NewEvent.js
- src/index.css
Lisäksi säädetty vähän css:ää sekä tehty uudelleen jo kerran tehdyt ja kadotetut validoinnit.
> Show single event ui

- src/App.js
- src/components/EventCard.js
- src/components/ListEvents.js
Delete single event, can't delete event group yet!
> Delete single event

- src/components/EventCard.js
- src/components/NewEvent.js
Added autoOk to pickers, so no need to push ok anymore after selection. Changed style to landscape, works better with devtools... Date cannot be picked from past anymore.
> Pickers fix

- src/components/Activity.js
- src/components/NewEvent.js
fixed validators once again... fixed small bug from Activity.js
> Validation fix

- src/components/NewEvent.js
- src/components/SearchBar.js
Also tried to fix double calendar problem in mobile.
> Event default one hour

- src/App.js
- src/api-config.js
- src/components/Activity.js
- src/components/EventCard.js
- src/components/NewEvent.js
- src/components/SearchBar.js
Once this has been confirmed to work in production ill clean backend since it wont need https on development envirement
> baseurl hidden in config file now

- src/App.js
- src/functions/searchBarFiltering.js
Reverts partio-scout/tosu-frontend#46
> Revert "Searchbar filterv3"

- src/App.js
- src/components/Activity.js
- src/components/AppBar.js
- src/components/BufferZone.js
- src/components/EventCard.js
- src/components/SearchBar.js
- src/components/TopSearchBar.js
- src/index.css
- src/utils/ActivityMapper.js
- src/utils/NormalizeActivitiesData.js
Lots of stuff here, refactored Activity and TopSearchBar and BufferZone, fixed some bugs and made a new one.
> Activity to draggable

- src/components/Activity.js
- src/services/pof.js
and use icons from pof-backend
> Color code mandatory activites

- src/App.js
- src/components/Activity.js
- src/components/BufferZone.js
- src/components/EventCard.js
- src/components/EventForm.js
- src/index.css
When activity is dragged, droppable areas are colored green.
> Dnd colors

- src/components/Activity.js
- src/components/EventCard.js
- src/components/PlanCard.js
- src/reducers/planReducer.js
- src/services/plan.js
- src/store.js
Commitit tuli mystisesti tuplana, mutta ei kannata antaa sen häiritä...
> Use redux in selected plans

- package-lock.json
- package.json
- src/App.js
- src/components/ActivityPreview.js
Test for a new backend for drag and drop.
> Multibackend

- src/components/Activity.js
- src/components/ActivityPreview.js
> Better colors

- src/utils/NormalizeActivitiesData.js
Edit normalizer to return only list of all the activities. This is NOT used anywhere yet but might be helpful when changig to filledpof data from backend.
> Change normalizer to return only list of activities

- src/App.js
- src/components/StatusMessage.js
- src/functions/findActivity.js
- src/reducers/statusMessageReducer.js
- src/services/activities.js
- src/utils/createStatusMessage.js
This is not depending on selected tarppo yet
> Show how many mandatory and non mandatory activities is selected

- src/App.js
- src/components/ActivityPreview.js
- src/components/BufferZone.js
- src/components/GoogleButtons.js
- src/components/StatusMessage.js
- src/components/TreeSearchBar.js
- src/components/UserInfo.js
- src/reducers/statusMessageReducer.js
- src/utils/createStatusMessage.js
Show user info what to do next.
Also cleaning up some warnings from console
> User guidance in status box

- src/App.js
- src/components/Activity.js
- src/components/AppBar.js
- src/components/EventCard.js
- src/components/NewEvent.js
- src/components/StatusMessage.js
- src/components/TreeSearchBar.js
- src/index.css
- src/reducers/statusMessageReducer.js
- src/reducers/taskgroupReducer.js
- src/store.js
- src/utils/createStatusMessage.js
- Show status of mandatory and non-mandatory tasks based on selected tarppo
- Show event's activities in eventcard header also, so no need to click events open when dragging and dropping activities
- Fix layout of topbar for desktop, mobile view needs a better solution later
> Status based on tarppo

- src/components/EventCard.js
- src/components/StatusMessage.js
- src/index.css
- src/reducers/pofTreeReducer.js
and also show what warning means on desktop
> Few fixes in mobile ui

- package-lock.json
- src/components/EventForm.js
- src/utils/ValidatedDatePicker.js
- src/utils/ValidatedTimePicker.js
* using updated react-material-ui-form-validator for validation
* created classes for validated date and time picker
> Validation rules for DatePicker and TimePicker components

- src/components/Activity.js
- src/components/BufferZone.js
- src/components/EventCard.js
Drag and drop works. Activities now move locally before getting response from backend.
> Improved dnd

- package-lock.json
- package.json
- src/App.js
- src/components/EventCalendar.js
- src/index.css
* Added react-big-calendar
* Organised App.js imports
* Using filters for determining active button... maybe there's a better way
* Renamed filter from PAST to ALL
> Calendar view with events

- src/api-config.js
New backend address for old frontend
> new pof api

- package-lock.json
- src/components/Calendar.js
- src/components/CalendarEvent.js
- src/components/DeleteEvent.js
- src/components/EventCard.js
- src/index.css
Major changes noted in commits. There's a problem with a faulty notification when editing an event in calendar view. This is due to a call to bufferzoneinitialization, which calendar doesn't define. I haven't fixed it since I haven't figured out the need for the function yet.
> Working popover buttons => testing-popovers

- src/components/DeleteEvent.js
- src/reducers/eventReducer.js
- src/services/eventgroups.js
Some issues with the naming, deleting an eventgroup did not work in master but this should fix it.
> deleteEventGroup fixes

- package-lock.json
- src/components/BufferZone.js
- src/components/Calendar.js
- src/components/StatusMessage.js
- src/index.css
- Scrollbar for left view
- new button with icon
- calendar scales for the window
- max width for event cards
> Statusbox scrollbar

- src/App.js
- src/components/Calendar.js
- src/components/DeleteEvent.js
- src/components/EditEvent.js
- src/components/EventCard.js
- src/components/KuksaEventCard.js
- src/components/NewEvent.js
- src/index.css
- src/reducers/eventReducer.js
Phase 1 of Kuksa integration. Events are fetched from Kuksa using Tapahtumat API.
* Added Kuksa page to Router, listing all events from Kuksa
* Ability to add a Kuksa event to Tosu (saved to db)
* Added KuksaEventCard component
* Added synced events
* Highlighted in blue
* Added skeleton for syncing back to Kuksa (sync switch & handlers)
* Not currently used, and editing synced events is disabled
* Editing a synced event is disabled at this stage
* Added kuksa event specific popup explanations
* Added a loading bar while fetching kuksa events (currently slows down fetching all events)
> Tapahtumat API: Sync events from Kuksa to Tosu

- src/components/Activities.js
- src/components/AddToPlan.js
- src/components/CalendarEvent.js
- src/components/EventCard.js
- src/components/EventList.js
- src/components/KuksaEventCard.js
- src/index.css
* Added grey color for kuksa event card
* Using card colors in calendar popover
* Don't show edit or delete buttons for kuksa events
* Disable dragging activities into kuksa events
> Calendar: Disable dragging activities into kuksa events, improve popover styling

- package-lock.json
- package.json
- src/App.js
- src/index.css
- src/reducers/filterReducer.js
Uses react-dates to filter events based on a date range.
Doesn't work with kuksa events yet.
> Date range filter

- package-lock.json
- package.json
- src/components/BufferZone.js
- src/components/Calendar.js
- src/components/CalendarEvent.js
- src/components/DeleteEvent.js
- src/components/EditEvent.js
- src/components/EventCard.js
- src/components/EventForm.js
- Only one popover at the time
- added padding for cards
- added icons to some buttons
- removed ugly pink colour
> Little fixes

- src/api-config.js
- src/components/StatusMessage.js
- src/functions/DropActivity.js
- src/functions/activityConverter.js
- src/index.css
- src/reducers/pofTreeReducer.js
- src/utils/createStatusMessage.js
- added some checks when parsing pof data -> frontend doesn't immediately crash if fetched pof data contains something unexpected
- fixed bugs in checking whether the activities are placed in correct order
- better warning messages when activities are in wrong order
> Pof tree fixes

- src/components/Activities.js
- src/functions/DropActivity.js
- Call pofTreeUpdate after the activities are actually moved or deleted
> Fix a bug that allows adding same activity twice

- src/components/MobileAppbar.js
- src/index.css
Fixes unselectable tarppo and width overflows
> Mobile fixes

- src/stylesheets/container.css
- src/stylesheets/content.css
- src/stylesheets/index.css
Event cards are now always full width.
> Full width event cards

- .travis.yml
- package-lock.json
- package.json
- src/App.js
- src/components/Login.js
- src/index.js
- src/reducers/loadingReducer.js
- src/store.js
Moved login functionality to its own component. Moved Google Api key to .env file. Moved app loading state to redux.
> Login component

- src/components/EventCard.js
- src/stylesheets/button.css
changed info button to render savebutton on top
> Info button fixes

- package-lock.json
- package.json
- src/components/EventCard.js
- src/components/MobileAppbar.js
Fixed issues on mobile appbar that were related to the new datastructure.
> Accidentaly fixed mobile issues on this branch merging here.

- src/components/Activities.js
- src/reducers/activityReducer.js
Also removed one debug console.log.
> Deleting activity from event now moves the activity to buffer

- Dockerfile
- src/App.js
adding docker and docker-compose for some advanced CI tricks.
> Dockerfile and docker compose

- src/components/AddToPlan.js
- src/components/DeleteEvent.js
- src/components/DeleteTosuButton.js
Kuksa eventin lisäämisen, yksittäisen ja toistuvan eventin poiston ja tosun poiston nappuloiden värejä muutettu. Kaikki peruuta -napit harmaita, kuksa eventin lisääminen tummansininen (primary), muut poista -napit punaisia paitsi toistuvan eventin poistossa yksittäisen toistuvan eventin poisto-nappi on vaaleampi sininen (secondary).
> added colors to buttons

- src/components/Activities.js
- src/components/Activity.js
- src/components/BufferZone.js
No longer returns `<div />` when buffer is empty. 
Doesn't show ''TYHJENNÄ' button if the buffer is empty.
> Can drag activities from Event to empty BufferZone

- src/components/TosuDrawer.js
- src/functions/tosuChange.js
> clearing buffer on tosu change

- src/App.js
- src/components/ActivitiesSidebar.js
- src/components/ToolbarSpacer.js
Removes console errors regarding unknown styles in `style` attribute.
> Add ToolbarSpacer
